### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by GeorgeS2019** [kaiidams/Voice100AndroidApp#19]
I took the test waves from https://github.com/kaiidams/NeMoOnnxSharp and sent that through the latest Voice100 ASR. I have interesting results. 

Not sure I am configuring the wave in correctly. 

Are the waveform data that pipes into the Voice100 ASR and NeMOOnnxSharp compatible and interchangeable?

**Comment by kaiidams** [comment]
16bit 16000Hz waveform is converted to 64-dim Mel Spectrogram and passed to ONNX model for both QuartsNet and Voice100 ASR, however, how Mel Spectrograms are calculated differently. QuartsNet uses HTK style and Voice 100 is compatible with Google YamNet.
