### ISSUE TITLE
Windows build for voice100_native and webrtc_vad

### ISSUE THREAD

**Issue by GeorgeS2019** [kaiidams/Voice100AndroidApp#20]
[Windows build for voice100_native](https://github.com/kaiidams/Voice100AndroidApp/pull/17)

Please check the provided [Window native binary of x64.](https://github.com/kaiidams/Voice100AndroidApp/tree/main/Voice100AndroidApp/lib/x86_64) I think the binary files start with ELF.

**Comment by kaiidams** [comment]
x64 DLLs included Voice100AndroidApp are for x64 Android. I've built webrtc_vad for Windows in [this repo](https://github.com/kaiidams/webrtc_vad/releases/tag/v0.1). It can link with C# but I didn't confirm if it correctly works yet.

**Comment by kaiidams** [comment]
Windows build for voice100_native.dll is available in [this repo](https://github.com/kaiidams/Voice100Sharp/tree/main/Voice100App/runtimes/win-x64/native)

**Comment by GeorgeS2019** [comment]
@kaiidams Are you aware of [Microsoft Jupyter-like .NET notebook](https://github.com/dotnet/interactive) and the advantages that come with it?

**Comment by kaiidams** [comment]
@GeorgeS2019 I noticed [ICSharpCore](https://github.com/SciSharp/ICSharpCore) and [dotnet-try](https://github.com/dotnet/try), but not [interactive](https://github.com/dotnet/interactive). Thank you for letting me know. I'll take a look.
