### ISSUE TITLE
How I can find which language is in the audio file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [kaiidams/Voice100AndroidApp#22]
Hello:
I have a number of audios file (.WAV format), but each of the audio file could have different language, like: Chinese, English, French, German, Spanish.
How I can use the repo to find which language is recorded in the audio file, so I can lauch sepecific voice recognition program to recognize it?
I am using C# on Windows 10.
Thanks,

**Comment by kaiidams** [comment]
Hi, language detection is not implemented in this depos, you could try using cloud services
https://docs.microsoft.com/en-us/azure/cognitive-services/Speech-Service/language-identification?tabs=once&pivots=programming-language-csharp
