### ISSUE TITLE
Repurpose Voice100 to LipSync

### ISSUE THREAD

**Issue by GeorgeS2019** [kaiidams/Voice100AndroidApp#9]
[A **MFCC**-based LipSync plugin for Unity using Burst Compiler](https://github.com/hecomi/uLipSync)

Hope you are interested. The c# game community e.g. Godot needs a low cost STT and TTS to drive lip sync.

**Comment by kaiidams** [comment]
@GeorgeS2019 Sounds interesting. Unity has Barracuda to run ONNX models. Does Godot have something similar?

**Comment by GeorgeS2019** [comment]
@kaiidams 
https://github.com/JimFFM/ml-hackathon-2021/

Godot c#  provide ML.NET service that takes ONNX input

**Comment by GeorgeS2019** [comment]
@kaiidams 

We need 
- **Voice recognition** to provide real time command to navigate the SpaceX starship and 
- **Text To speech** to provide computer voice feedback how good is the landing, how close to the target! 

![142358633-33c33c02-7e19-4ce0-b9a8-1148e8c8017d](https://user-images.githubusercontent.com/49812372/147111750-5c85b342-8656-4751-9fb0-6c997c0f86f8.gif)
